name: 'Terraform Configuration Drift Detection'

on:
  workflow_dispatch:
  schedule:
    - cron: '41 3 * * *' # runs nightly at 3:41 am

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  issues: write

# These environment variables are used by the terraform azure provider to setup OIDC authenticate.
env:
  ARM_CLIENT_ID: "${{ vars.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ vars.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ vars.AZURE_TENANT_ID }}"
  TF_VAR_allowed_source_ip: ${{ vars.TF_VAR_ALLOWED_SOURCE_IP }}
  TF_VAR_tf_principal_object_id: ${{ vars.TF_PRINCIPAL_OBJECT_ID }}
  TF_VAR_plan_principal_object_id: ${{ vars.PLAN_PRINCIPAL_OBJECT_ID }}

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
    defaults:
      run:
        working-directory: terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v7

    # Login to Azure using OIDC
    - name: Azure login with OIDC
      uses: azure/login@v3
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    # Install the latest version of the Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: '~1.15'
        terraform_wrapper: false

    # Initialize a new or existing Terraform working directory
    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
    - name: Terraform Plan
      id: tf-plan
      run: |
        export exitcode=0
        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?

        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

        if [ $exitcode -eq 1 ]; then
          echo Terraform Plan Failed!
          exit 1
        else
          exit 0
        fi

    # Save plan to artifacts
    - name: Publish Terraform Plan
      uses: actions/upload-artifact@v7
      with:
        name: tfplan
        path: terraform/tfplan

    # Create string output of Terraform Plan
    - name: Create String Output
      id: tf-plan-string
      run: |
        TERRAFORM_PLAN=$(terraform show -no-color tfplan)

        delimiter="$(openssl rand -hex 8)"
        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo '```terraform' >> $GITHUB_OUTPUT
        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
        echo '```' >> $GITHUB_OUTPUT
        echo "</details>" >> $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT

    # Publish Terraform Plan as task summary
    - name: Publish Terraform Plan to Task Summary
      env:
        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
      run: |
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

    # If drift detected, create or update a GitHub Issue
    - name: Create or Update Drift Issue
      if: steps.tf-plan.outputs.exitcode == 2
      uses: actions/github-script@v9
      env:
        SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const body = `${process.env.SUMMARY}`;
          const title = 'Terraform Configuration Drift Detected';
          const creator = 'github-actions[bot]'

          // Look to see if there is an existing drift issue
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            creator: creator,
            title: title
          })

          if( issues.data.length > 0 ) {
            const issue = issues.data[0]

            if ( issue.body == body ) {
              console.log('Drift Detected: Found matching issue with duplicate content')
            } else {
              console.log('Drift Detected: Found matching issue, updating body')
              github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: body
              })
            }
          } else {
            console.log('Drift Detected: Creating new issue')
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body
            })
          }

    # If no drift, close any open drift issues
    - name: Close Drift Issue
      if: steps.tf-plan.outputs.exitcode == 0
      uses: actions/github-script@v9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const title = 'Terraform Configuration Drift Detected';
          const creator = 'github-actions[bot]'

          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            creator: creator,
            title: title
          })

          if( issues.data.length > 0 ) {
            const issue = issues.data[0]

            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              state: 'closed'
            })
          }

    # Mark the workflow as failed if drift detected
    - name: Error on Drift
      if: steps.tf-plan.outputs.exitcode == 2
      run: exit 1